# Discord RPC Wrapper by JoshiCodes

defaults:
  rpc:
    clientId: 1073729155625144442
    state: "github.com/JoshiCodes/RPCWrapper"
    details: "created by @JoshiCodes on GitHub"


# Everything regarding timings
timings:
  updateInterval: 1000


# Everything happening at Startup
startup:
  preset: example # Optional, leave blank or remove/comment to use default


# Custom Presets, you can add as many as you want
# You can load them by using the "preset" option in the startup section or by typing "preset <name>" in the console
presets:

  # Example Preset
  # Commented out or optional values can be removed
  example:
    #clientId: 123456789012345678      # Optional, leave blank or remove/comment to use default
    state: "Example State"             # Required
    details: "Example Details"         # Optional
    largeImage: "logo"                 # Optional, Be sure to add the image in the Developer Portal
    largeImageText: "Large Image Text" # Optional
    smallImage: "logo"                  # Optional, Be sure to add the image in the Developer Portal
    smallImageText: "Small Image Text" # Optional
    startTimestamp: 0                  # Optional, 0 = current time
    endTimestamp: -1                   # Optional, -1 or 0 = no end time